### Get all mods
GET {{baseUrl}}/mods

### Add a new mod
POST {{baseUrl}}/mods/add
apikey: 00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "modID": "test",
  "name": "Test Mod",
  "description": "",
  "websiteURL": "",
  "downloadURL": "",
  "issueURL": ""
}