### Get all mods
GET {{baseUrl}}/mods

### Add a new mod
POST {{baseUrl}}/mods/add
apikey: {{apiKey}}
Content-Type: application/json

{
  "modID": "test",
  "name": "Test Mod",
  "description": "",
  "websiteURL": "",
  "downloadURL": "",
  "issueURL": ""
}

### Update a mod
POST {{baseUrl}}/mods/edit/test
apikey: {{apiKey}}
Content-Type: application/json

{
  "name": "Test Mod",
  "description": "ABC",
  "websiteURL": "",
  "downloadURL": "",
  "issueURL": ""
}

### Get a mod
GET {{baseUrl}}/mods/test
