
### Get updates
GET {{baseUrl}}/updates/test

### Get updates with pageable
GET {{baseUrl}}/updates/test?amount=1&page=0

### Get an update
GET {{baseUrl}}/updates/test/1

### Add a new update
POST {{baseUrl}}/updates/test
apikey: {{apiKey}}
Content-Type: application/json

{
  "gameVersion": "1.18.2",
  "version": "1.0.0+1.18.2",
  "updateMessages": ["Test message"],
  "releaseType": "beta",
  "tags": ["recommended"],
  "modLoader": "fabric"
}
