server:
  error:
    path: /error

management:
  server:
    port: 8070
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
  profiles:
    active: prod